In [1]:
import ctypes
import numpy as np
from lib import *

In [2]:
X = np.array([
    [5,17],
    [6,20],
    [4,14],
    [3,11],
    [2,8],
    [10,32],
    [7,23],
    [8,27],
    [11,35],
])
X_size = len(X)
Y = X[:,1]
X = X[:,0]
print(Y)
print(X)

[17 20 14 11  8 32 23 27 35]
[ 5  6  4  3  2 10  7  8 11]


In [3]:
all_training_inputs = np.float64(X.flatten())
all_training_expected_outputs = np.float64(Y.flatten())
print(all_training_inputs)
print(type(all_training_inputs))


[ 5.  6.  4.  3.  2. 10.  7.  8. 11.]
<class 'numpy.ndarray'>


In [4]:
size_W = 2

In [5]:
model_linear = create_linear_model(size_W)

In [6]:
print(model_linear)

29660384


In [7]:
X_test = np.array([5.0])
predict_linear_model(model_linear, X_test, 1)

 predict : [5.0], shape=[1], strides=[1], layout=CFcf (0xf), const ndim=1
PREDICT : x : [1.0, 5.0], shape=[2], strides=[1], layout=CFcf (0xf), const ndim=1, W : [0.3200392142019215, -0.646282705516362], shape=[2], strides=[1], layout=CFcf (0xf), const ndim=1


-2.9113743133798886

In [8]:
train_linear_model(model_linear, 
                   all_training_inputs, X_size, 1,
                   all_training_expected_outputs, X_size, 
                   0.001, 5000, False)

new weight : [1.9642784364371293, 3.0235860775348202]


In [9]:
X_test = np.array([5.0])
predict_linear_model(model_linear, X_test, 1)

 predict : [5.0], shape=[1], strides=[1], layout=CFcf (0xf), const ndim=1
PREDICT : x : [1.0, 5.0], shape=[2], strides=[1], layout=CFcf (0xf), const ndim=1, W : [1.9642784364371293, 3.0235860775348202], shape=[2], strides=[1], layout=CFcf (0xf), const ndim=1


17.08220882411123