In [1]:
import ctypes
import numpy as np
import csv
from lib import *

from modules.ml.ml.models.linear.lib import test_linear_model, create_linear_model, train_linear_model, \
    predict_linear_model

### Electro TRAIN

In [2]:
from modules.ml.ml.models.linear.lib import loadDataSet

all_training_inputs, all_training_expected_outputs, X_size, X_row_size = loadDataSet('OxydDataset_32_1/electro_train.csv')

print(all_training_inputs)
print(all_training_expected_outputs)
print(X_row_size)
print(X_size)



[  0.   0.   0. ... 152. 196. 165.]
[1. 1. 1. ... 0. 0. 0.]
1024
2418


In [3]:
model_linear = create_linear_model(X_size)

In [ ]:
train_linear_model(model_linear, 
                   all_training_inputs, X_size, X_row_size,
                   all_training_expected_outputs, X_size, 
                   0.1, 50000, True)

In [7]:
x_test = test_linear_model(model_linear, 
                           X, X_size, 2,
                           Y, X_size, 0.1, True)
print(x_test)

[[1. 1.]
 [2. 3.]
 [3. 3.]]
100.0


In [7]:
X = np.array([
        [1.0, 8.0],
        [4.0, 2.0],
        [5.0, 6.0]
    ])
X_size = len(X)

Y = np.array([
        [0.0],
        [0.0],
        [1.0]
    ])
print(X_size)

3


In [9]:
all_training_inputs = np.float64(X.flatten())
all_training_expected_outputs = np.float64(Y.flatten())


In [10]:
size_W = 3

In [11]:
model_linear = create_linear_model(size_W)

In [12]:
print(model_linear)

1783072539888


In [13]:
train_linear_model(model_linear, 
                   all_training_inputs, 3, 2,
                   all_training_expected_outputs, 3, 
                   0.01, 50000, True)

In [14]:
X1_test = np.float64(np.array([1.0, 8.0]))
predict_linear_model(model_linear, X1_test, 2, True)

0.0

In [15]:

x_test = test_linear_model(model_linear,
                           X, X_size, 2,
                           Y, X_size, 0.1, True)
print(x_test)

[[1. 8.]
 [4. 2.]
 [5. 6.]]
100.0


# Linear Multiple

In [16]:
X = np.concatenate([np.random.random((50,2)) * 0.9 + np.array([1, 1]), np.random.random((50,2)) * 0.9 + np.array([2, 2])])
Y = np.concatenate([np.ones((50, 1)), np.ones((50, 1)) * -1.0])

X_size = len(X)

all_training_inputs = np.float64(X.flatten())
all_training_expected_outputs = np.float64(Y.flatten())

#2 col

In [17]:
model_linear = create_linear_model(3)

In [18]:
train_linear_model(model_linear, 
                   all_training_inputs, 3, 2,
                   all_training_expected_outputs, 3, 
                   0.01, 50000, True)

In [19]:
x_test = test_linear_model(model_linear, 
                           all_training_inputs, X_size, 2,
                           all_training_expected_outputs, X_size, 0.1, True)
print(x_test)

[1.16687447 1.30124503 1.62853978 1.42574446 1.46639552 1.52371252
 1.50180369 1.14594863 1.10700476 1.04192417 1.77751328 1.67393403
 1.8246611  1.33711513 1.60929283 1.79806257 1.71439229 1.25593479
 1.02891904 1.72028532 1.50601741 1.05623131 1.67661477 1.53240353
 1.59548925 1.58667257 1.79260962 1.15091997 1.60125236 1.80164493
 1.24936812 1.078574   1.76203572 1.16564821 1.20764313 1.19820306
 1.39502277 1.73667809 1.13552107 1.72320263 1.24917787 1.59582612
 1.39180412 1.11437203 1.52352113 1.03503992 1.87126619 1.8881928
 1.15999805 1.49479426 1.14662241 1.70723978 1.31728834 1.29288785
 1.83942628 1.34406255 1.83733983 1.31747121 1.46536954 1.80964957
 1.1073297  1.07608653 1.38128705 1.51367719 1.7158307  1.69330788
 1.45308015 1.84215266 1.86994202 1.06214185 1.21885479 1.75999005
 1.80434593 1.30163329 1.67751575 1.82763012 1.41423842 1.76147508
 1.86713831 1.27813992 1.25588703 1.21744792 1.41092625 1.68829516
 1.6023194  1.193556   1.6128878  1.41647149 1.56113899 1.68878