In [1]:
from lib import *
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [2]:
def accuracy(y_true, y_pred):
    y_true = np.argmax(y_test, axis=1)
    y_pred = np.argmax(y_pred, axis=1)
    correct = 0
    total = len(y_true)
    for true, pred in zip(y_true, y_pred):
        if true == pred:
            correct += 1
    return correct / total

In [3]:
data = np.genfromtxt('data/dataset_waveshow_10.csv', delimiter=',')
train = data[:, 0:data.shape[1] - 1]
test = data[:, -1].reshape(-1, 1)

ct = ColumnTransformer([('encoder', OneHotEncoder(), [0])], remainder='passthrough')
y = ct.fit_transform(test)
y[y == 0] = -1

# Normalisation des noms de variable
X = train / 255

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)



In [4]:
X_train.shape , y_train.shape , X_test.shape , y_test.shape

((4018, 100), (4018, 3), (1005, 100), (1005, 3))

In [5]:
model = create_mlp_model(np.array([X_train.shape[1], 50, 50, y_train.shape[1]]))

In [6]:
train_mlp_model(
    model,
    X_train,
    y_train,
    0.0003,
    3,
    True,
    b"test"
)

In [7]:
test_preds = [predict_mlp_model(model, x, True, 3) for x in X_test]
test_preds

[array([-0.30740702, -0.19937946, -0.40601911]),
 array([-0.40187448, -0.23365182, -0.35283145]),
 array([-0.31216676, -0.68866082,  0.08794649]),
 array([-0.12734544, -0.62787372, -0.17149782]),
 array([-0.65023964, -0.79722528,  0.21639975]),
 array([-0.34342126, -0.08197678, -0.67306887]),
 array([-0.37660036, -0.14337499, -0.50518132]),
 array([-0.51595956, -0.45395558, -0.18408329]),
 array([-0.47328112, -0.71060039, -0.04275544]),
 array([-0.41641901, -0.29875578, -0.34081485]),
 array([-0.38798744, -0.11716019, -0.51065583]),
 array([-0.69819335, -0.54339128, -0.00226055]),
 array([-0.51450546,  0.03763539, -0.25883742]),
 array([-0.34551933, -0.74408297, -0.08191353]),
 array([-0.4524837 , -0.37408279, -0.237129  ]),
 array([-0.35866589, -0.09559862, -0.54452995]),
 array([-0.37667873, -0.15030091, -0.42358496]),
 array([-0.31686292, -0.05505486, -0.57798472]),
 array([-0.59224306, -0.02602337, -0.62289392]),
 array([-0.32438515, -0.24867698, -0.65535611]),
 array([-0.56209614,

In [8]:
acc = accuracy(y_test, test_preds)
acc

0.4507462686567164

In [28]:
save_mlp_model(model, b"oxyd_beta.model")