In [1]:
import ctypes
import numpy as np
from lib import *

In [2]:
""" X = np.array([
        [1.0, 1.0],
        [2.0, 3.0],
        [3.0, 3.0]
    ])
X_size = len(X)

Y = np.array([
        [1.0],
        [-1.0],
        [-1.0]
    ])
 """
#####test for output 3 dimension

X = np.random.random((500, 2)) * 2.0 - 1.0
Y = np.array([[1, 0, 0] if -p[0] - p[1] - 0.5 > 0 and p[1] < 0 and p[0] - p[1] - 0.5 < 0 else 
              [0, 1, 0] if -p[0] - p[1] - 0.5 < 0 and p[1] > 0 and p[0] - p[1] - 0.5 < 0 else 
              [0, 0, 1] if -p[0] - p[1] - 0.5 < 0 and p[1] < 0 and p[0] - p[1] - 0.5 > 0 else 
              [0, 0, 0]for p in X])

X = X[[not np.all(arr == [0, 0, 0]) for arr in Y]]
Y = Y[[not np.all(arr == [0, 0, 0]) for arr in Y]]


all_training_inputs = np.float64(X.flatten())
all_training_expected_outputs = np.float64(Y.flatten())

npl = np.array([2, 3])
npl_size = len(npl)


sample_inputs = np.array(X[0])
sample_inputs_size = len(sample_inputs)

In [3]:
all_training_expected_outputs

array([0., 1., 0., ..., 1., 0., 0.])

In [4]:
sample_inputs

array([0.71150096, 0.48142241])

In [5]:
model_pointer = create_mlp_model(npl, npl_size)

predict = predict_mlp_model(model_pointer, sample_inputs , sample_inputs_size, True , npl)
print(predict)

[0.65458937 0.65458937 0.65458937]


In [6]:

train_mlp_model(model_pointer, all_training_inputs, len(X), len(X[0]), all_training_expected_outputs, len(Y[0]), 0.1, 1000, True)
predict = predict_mlp_model(model_pointer, sample_inputs , sample_inputs_size, True , npl)
print(predict)
#delete_mlp_model(model_pointer)
delete_float_array(predict, npl)

[-0.24078191  0.78853927  0.47353256]


In [6]:
delete_mlp_model(model_pointer)


In [4]:
save_mlp_model(model_pointer, "test.mlp")

MLP model saved to file: test.mlp


In [ ]:
import_model = load_mlp_model("test.mlp")

: 

: 