In [1]:
import ctypes
import numpy as np
from lib import *

In [2]:
""" X = np.array([
        [1.0, 1.0],
        [2.0, 3.0],
        [3.0, 3.0]
    ])
X_size = len(X)

Y = np.array([
        [1.0],
        [-1.0],
        [-1.0]
    ])
 """
#####test for output 3 dimension

X = np.random.random((500, 2)) * 2.0 - 1.0
Y = np.array([[1, 0, 0] if -p[0] - p[1] - 0.5 > 0 and p[1] < 0 and p[0] - p[1] - 0.5 < 0 else 
              [0, 1, 0] if -p[0] - p[1] - 0.5 < 0 and p[1] > 0 and p[0] - p[1] - 0.5 < 0 else 
              [0, 0, 1] if -p[0] - p[1] - 0.5 < 0 and p[1] < 0 and p[0] - p[1] - 0.5 > 0 else 
              [0, 0, 0]for p in X])

X = X[[not np.all(arr == [0, 0, 0]) for arr in Y]]
Y = Y[[not np.all(arr == [0, 0, 0]) for arr in Y]]


all_training_inputs = np.float64(X.flatten())
all_training_expected_outputs = np.float64(Y.flatten())

npl = np.array([2, 3])
npl_size = len(npl)


sample_inputs = np.array(X[0])
sample_inputs_size = len(sample_inputs)

In [6]:
Y[45]

array([1, 0, 0])

In [3]:
all_training_expected_outputs

array([1., 0., 0., ..., 0., 1., 0.])

In [4]:
sample_inputs

array([-0.82316076, -0.3940344 ])

In [5]:
model_pointer = create_mlp_model(npl, npl_size)

predict = predict_mlp_model(model_pointer, sample_inputs , sample_inputs_size, True , npl)
print(predict)

create_mlp_model
w: [[], [[0.0, 1.3372296076667154, -0.588569883948526, 1.4066435232092467], [0.0, -0.43812343028357836, 1.0839490316390654, -2.3593209790377796], [0.0, -0.0017339373863660698, -0.5062941820860668, 0.8633453192838477]]]
create_mlp_model done
[ 0.76853551 -0.03742767  0.09377515]
preditiction [0.7685355070071443, -0.037427667349676334, 0.09377514798777214]


In [5]:

#train_mlp_model(model_pointer, all_training_inputs, len(X), len(X[0]), all_training_expected_outputs, len(Y[0]), 0.1, 1000, True)
predict = predict_mlp_model(model_pointer, X[45] , sample_inputs_size, True , npl)
print(predict)
#delete_mlp_model(model_pointer)
delete_float_array(predict, npl)

preditiction [0.7046085337036024, 0.0663292139738045, 0.07374470790995362]
[0.70460853 0.06632921 0.07374471]


In [6]:
delete_mlp_model(model_pointer)


In [4]:
model_pointer = load_mlp_model("test.mlp")

In [ ]:
# read first image from the dataset and show it

