In [1]:
import ctypes
import numpy as np
from lib import *

In [2]:
""" X = np.array([
        [1.0, 1.0],
        [2.0, 3.0],
        [3.0, 3.0]
    ])
X_size = len(X)

Y = np.array([
        [1.0],
        [-1.0],
        [-1.0]
    ])
 """
#####test for output 3 dimension

X = np.random.random((500, 2)) * 2.0 - 1.0
Y = np.array([[1, 0, 0] if -p[0] - p[1] - 0.5 > 0 and p[1] < 0 and p[0] - p[1] - 0.5 < 0 else 
              [0, 1, 0] if -p[0] - p[1] - 0.5 < 0 and p[1] > 0 and p[0] - p[1] - 0.5 < 0 else 
              [0, 0, 1] if -p[0] - p[1] - 0.5 < 0 and p[1] < 0 and p[0] - p[1] - 0.5 > 0 else 
              [0, 0, 0]for p in X])

X = X[[not np.all(arr == [0, 0, 0]) for arr in Y]]
Y = Y[[not np.all(arr == [0, 0, 0]) for arr in Y]]


all_training_inputs = np.float64(X.flatten())
all_training_expected_outputs = np.float64(Y.flatten())

npl = np.array([2, 3])
npl_size = len(npl)


sample_inputs = np.array(X[0])
sample_inputs_size = len(sample_inputs)

In [3]:
model_pointer = create_mlp_model(npl, npl_size)

predict = predict_mlp_model(model_pointer, sample_inputs , sample_inputs_size, True , npl)
print(predict)

create_mlp_model
w: [[], [[0.0, 2.227120130119883, 0.6199086752896343, -1.104193104538968], [0.0, -0.021362628984519266, 0.13778817458501313, 1.6703561182851336], [0.0, -0.2815853067260653, -0.3527217010534829, 0.7582355843803698]]]
create_mlp_model done
[ 0.9689887   0.38767993 -0.71648347]


In [4]:

train_mlp_model(model_pointer, all_training_inputs, len(X), len(X[0]), all_training_expected_outputs, len(Y[0]), 0.1, 1000, True)
predict = predict_mlp_model(model_pointer, sample_inputs , sample_inputs_size, True , npl)
print(predict)
delete_float_array(predict, npl)
save_mlp_model(model_pointer, "test.mlp")
delete_mlp_model(model_pointer)


train_mlp_model
[ 0.19532748  0.87165299 -0.13661799]
train_mlp_model done
delete_float_array done
save_mlp_model done
delete_mlp_model done


In [5]:
model_pointer = load_mlp_model("test.mlp")
train_mlp_model(model_pointer, all_training_inputs, len(X), len(X[0]), all_training_expected_outputs, len(Y[0]), 0.1, 1000, True)
predict = predict_mlp_model(model_pointer, sample_inputs , sample_inputs_size, True , npl)
print(predict)
delete_float_array(predict, npl)
delete_mlp_model(model_pointer)


load_mlp_model done
train_mlp_model
train_mlp_model done
[ 0.32589362  0.7933914  -0.18988113]
delete_float_array done
delete_mlp_model done
