In [1]:
import ctypes
import numpy as np
from lib import *

In [9]:
""" X = np.array([
        [1.0, 1.0],
        [2.0, 3.0],
        [3.0, 3.0]
    ])
X_size = len(X)

Y = np.array([
        [1.0],
        [-1.0],
        [-1.0]
    ])
 """
#####test for output 3 dimension

X = np.random.random((500, 2)) * 2.0 - 1.0
Y = np.array([[1, 0, 0] if -p[0] - p[1] - 0.5 > 0 and p[1] < 0 and p[0] - p[1] - 0.5 < 0 else 
              [0, 1, 0] if -p[0] - p[1] - 0.5 < 0 and p[1] > 0 and p[0] - p[1] - 0.5 < 0 else 
              [0, 0, 1] if -p[0] - p[1] - 0.5 < 0 and p[1] < 0 and p[0] - p[1] - 0.5 > 0 else 
              [0, 0, 0]for p in X])

X = X[[not np.all(arr == [0, 0, 0]) for arr in Y]]
Y = Y[[not np.all(arr == [0, 0, 0]) for arr in Y]]

from numpy import genfromtxt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

test_acappella = genfromtxt('data/acappella_test.csv', delimiter=',')
train_acappella = genfromtxt('data/acappella_train.csv', delimiter=',')
train_accoust = genfromtxt('data/accoust_train.csv', delimiter=',')
test_accoust = genfromtxt('data/accoust_test.csv', delimiter=',')
train_electro = genfromtxt('data/electro_train.csv', delimiter=',')
test_electro = genfromtxt('data/electro_test.csv', delimiter=',')

vec_aca = np.zeros(train_acappella.shape[0])
vec_aca=  vec_aca.reshape(train_acappella.shape[0], 1)
train_acappella = np.hstack((train_acappella,vec_aca ))

vec_acc = np.ones(train_accoust.shape[0])
vec_acc =  vec_acc.reshape(train_accoust.shape[0], 1)
train_accoust = np.hstack((train_accoust,vec_acc ))

vec_ele = np.ones(train_electro.shape[0])*2
vec_ele =  vec_ele.reshape(train_electro.shape[0], 1)
train_electro = np.hstack((train_electro,vec_ele ))


# contatenate train_acappella, train_accoust, train_electro as np array
train = np.concatenate((train_acappella, train_accoust, train_electro), axis=0)
data = train[:,0:train.shape[1]-1]
label = train[:,-1]
data = data/255

X, X_test, y_train, y_test = train_test_split(data, label, test_size=0.2, random_state=42,stratify=label)

y_train = y_train.reshape(y_train.shape[0], 1)
enc = OneHotEncoder(handle_unknown='ignore')
enc.fit(y_train)
Y = enc.transform(y_train).toarray()



print(X)
all_training_inputs = np.float64(X.flatten())
all_training_expected_outputs = np.float64(Y.flatten())

npl = np.array([3, 3])
npl_size = len(npl)


sample_inputs = np.array(X[0])
print(sample_inputs)
sample_inputs_size = len(sample_inputs)

[[0.00392157 0.         0.         ... 0.95294118 0.94117647 0.9372549 ]
 [0.00392157 0.         0.         ... 0.59607843 0.51372549 0.64313725]
 [0.00392157 0.         0.         ... 0.56470588 0.57254902 0.65098039]
 ...
 [0.00392157 0.         0.         ... 0.76470588 0.70196078 0.84313725]
 [0.         0.         0.         ... 0.85490196 0.91764706 0.91764706]
 [0.00392157 0.         0.         ... 0.6627451  0.6627451  0.60784314]]
[0.00392157 0.         0.         ... 0.95294118 0.94117647 0.9372549 ]


In [10]:
all_training_expected_outputs

array([0., 1., 0., ..., 0., 0., 1.])

In [11]:
sample_inputs

array([0.00392157, 0.        , 0.        , ..., 0.95294118, 0.94117647,
       0.9372549 ])

In [ ]:
model_pointer = create_mlp_model(npl, npl_size)

predict = predict_mlp_model(model_pointer, sample_inputs , sample_inputs_size, True , npl)
print(predict)
train_mlp_model(model_pointer, all_training_inputs, len(X), len(X[0]), all_training_expected_outputs, len(Y[0]), 0.1, 100000, True)
predict = predict_mlp_model(model_pointer, sample_inputs , sample_inputs_size, True , npl)
print(predict)
#delete_mlp_model(model_pointer)
delete_float_array(predict, npl)

[0.31596232 0.31596232 0.31596232]
[0.3941733  0.3641502  0.27643639]


: 

: 

In [4]:
delete_mlp_model(model_pointer)


In [4]:
save_mlp_model(model_pointer, "test.mlp")

MLP model saved to file: test.mlp


In [ ]:
import_model = load_mlp_model("test.mlp")

: 

: 